### Get all conflicts
GET {{host}}/api/conflicts

### Get a conflict by a specific ID
GET {{host}}/api/conflicts/1

### Create a new conflict
POST {{host}}/api/conflicts
Content-Type: application/json

{
  "task1Id": 1,
  "task2Id": 7
}

### Update an existing conflict
PUT {{host}}/api/conflicts/1
Content-Type: application/json

{
  "task1Id": 1,
  "task2Id": 3
}

### Delete an existing conflict
DELETE {{host}}/api/conflicts/1
