### Get All Obstacles
GET {{host}}/api/obstacles

### Get Obstacle by ID
GET {{host}}/api/obstacles/1

### Create Obstacle
POST {{host}}/api/obstacles
Content-Type: application/json

{
  "userId": 3,
  "taskId": 1,
  "fromDate": "2024-01-01",
  "toDate": "2024-01-10",
  "applicantDescription": "Some description"
}

### Update Obstacle
PATCH {{host}}/api/obstacles/1
Content-Type: application/json

{
"status": "APPROVED",
"recipientAnswer": "Agreed",
"recipientUserId": 4
}

### Delete Obstacle
DELETE {{host}}/api/obstacles/4
