### Get All Obstacles
GET {{host}}/api/obstacles

### Get Obstacle by ID
GET {{host}}/api/obstacles/1

### Get Obstacles by User ID
GET {{host}}/api/obstacles/user/3

### Create Obstacle
POST {{host}}/api/obstacles
Content-Type: application/json

{
  "userId": 20,
  "tasksIds": [38,39],
  "fromDate": "2024-04-01",
  "toDate": "2024-04-10",
  "applicantDescription": "Some description"
}

### Update Obstacle
PATCH {{host}}/api/obstacles/1
Content-Type: application/json

{
"status": "APPROVED",
"recipientAnswer": "Agreed",
"recipientUserId": 4
}

### Delete Obstacle
DELETE {{host}}/api/obstacles/4
