### Get all roles
GET {{host}}/api/roles

### GET roles by type
GET {{host}}/api/roles/types/SYSTEM

### Get a role by a specific ID
GET {{host}}/api/roles/1

### Create a new role
POST {{host}}/api/roles
Content-Type: application/json

{
  "name": "ROLE_ADMIN",
  "type": "SYSTEM"
}

### Update an existing role
PUT {{host}}/api/roles/7
Content-Type: application/json

{
  "name": "ROLE_SPIEWAJACY",
  "type": "TASK_PERFORMER"

}

### Delete an existing role
DELETE {{host}}/api/roles/1
