### Get all schedules
GET http://localhost:8080/api/schedules

### Get current schedules
GET http://localhost:8080/api/schedules/current

### Get schedule by ID
GET http://localhost:8080/api/schedules/1

### Get schedules by userID
GET http://localhost:8080/api/schedules/user/5

### Create a new schedule
POST http://localhost:8080/api/schedules
Content-Type: application/json

{
  "taskId": 2,
  "userId": 4,
  "date": "2024-01-05"
}

#### Update an existing schedule by ID
PUT http://localhost:8080/api/schedules/2
Content-Type: application/json

{
  "taskId": 1,
  "userId": 4,
  "date": "2023-01-13"
}

### Delete schedule by ID
DELETE http://localhost:8080/api/schedules/1
