### Get all schedules
GET {{host}}/api/schedules

### Get current schedules
GET {{host}}/api/schedules/current

### Get schedule by ID
GET {{host}}/api/schedules/1

### Get schedules by userID
GET {{host}}/api/schedules/user/5

### Get schedules by date weeks
GET {{host}}/api/schedules/available-tasks?from=05-02-2024&to=11-02-2024

### Get schedules by user for specified week
GET {{host}}/api/schedules/available-tasks/users/51?from=26-02-2024&to=03-03-2024

### Get schedules by supervisor and date weeks
GET {{host}}/api/schedules/available-tasks/by-supervisor/ROLE_KANTOR?from=05-02-2024&to=11-02-2024

### Get user's dependencies for task creation
GET {{host}}/api/schedules/task/11/user-dependencies?from=05-02-2024&to=11-02-2024

### Create a new schedule
POST {{host}}/api/schedules
Content-Type: application/json

{
  "taskId": 2,
  "userId": 4,
  "date": "2024-01-05"
}

### Create a new schedule where task is in conflict with existing schedule, however we ignore conflicts
POST {{host}}/api/schedules?ignoreConflicts=true
Content-Type: application/json

{
  "taskId": 1,
  "userId": 4,
  "date": "2024-01-05"
}

### Create a new schedule for task for whole period
POST {{host}}/api/schedules/forWholePeriod?ignoreConflicts=true
Content-Type: application/json

{
  "taskId": 11,
  "userId": 4,
  "fromDate": "2024-01-05",
  "toDate": "2024-01-10"
}

### Create a new schedule for task for daily period
POST {{host}}/api/schedules/forDailyPeriod?ignoreConflicts=false
Content-Type: application/json

{
  "taskId": 13,
  "userId": 19,
  "weekStartDate": "2024-02-05",
  "weekEndDate": "2024-02-11",
  "taskDate": "2024-02-07"
}

#### Update an existing schedule by ID
PUT {{host}}/api/schedules/2
Content-Type: application/json

{
  "taskId": 1,
  "userId": 4,
  "date": "2023-01-13"
}

### Delete schedule by ID
DELETE {{host}}/api/schedules/1
