### Get all tasks
GET {{host}}/api/tasks

### Get all tasks short info
GET {{host}}/api/tasks/shortInfo

### Get a task by a specific ID
GET {{host}}/api/tasks/1

### Create a new task
POST {{host}}/api/tasks
Content-Type: application/json

{
  "name": "Wash dishes",
  "participantsLimit": 10,
  "permanent": true,
  "participantForWholePeriod": false,
  "allowedRoleNames": ["ROLE_USER"],
  "supervisorRoleNames": ["ROLE_USER"],
  "daysOfWeek": ["MONDAY", "WEDNESDAY", "FRIDAY"]
}

### Update an existing task
PUT {{host}}/api/tasks/1
Content-Type: application/json

{
  "name": "UpdatedTask",
  "participantsLimit": 15,
  "permanent": false,
  "participantForWholePeriod": true,
  "allowedRoleNames": ["ROLE_USER", "ROLE_ADMIN"],
  "supervisorRoleNames": ["ROLE_ADMIN"],
  "daysOfWeek": ["TUESDAY", "THURSDAY"]
}

### Delete an existing task
DELETE {{host}}/api/tasks/1
