### GET active sessions
GET {{host}}/api/users/activeSessions

### GET Check current user
GET {{host}}/api/users/current/check

### GET Current user
GET {{host}}/api/users/current

### Get all users
GET {{host}}/api/users

### Get all users short info
GET {{host}}/api/users/shortInfo

### Get a user by a specific ID
GET {{host}}/api/users/74

### POST logout
POST {{host}}/api/users/logout

### POST login
POST {{host}}/api/users/login
Content-Type: application/json

{
  "email": "funcad@mail9.com",
  "password": "87654321"
}

### POST login
POST {{host}}/api/users/login
Content-Type: application/json

{
  "email": "initDom@mail.com",
  "password": "DominikaninOP"
}

### POST register
POST {{host}}/api/users/register
Content-Type: application/json

{
  "name": "Joe",
  "surname": "Black",
  "email": "funcad@mail9.com",
  "password": "12345678"
}

### POST register-dev
POST {{host}}/api/users/register-dev
Content-Type: application/json

{
  "name": "Frank99",
  "surname": "Cadillac",
  "email": "funcad@mail99.com",
  "password": "12345678",
  "roleNames": ["ROLE_USER", "ROLE_ADMIN", "ROLE_SPIEWAJACY"]
}

### Verify and assign roles to user
PUT {{host}}/api/users/34/verification/assignRoles
Content-Type: application/json

["ROLE_DZIEKAN", "ROLE_SPIEWAJACY"]

### Change user password
PATCH {{host}}/api/users/33/password
Content-Type: application/json

{
  "newPassword": "12345678"
}

### Create a new user
POST {{host}}/api/users
Content-Type: application/json

{
  "email": "new@example.com",
  "password": "password123",
  "name": "John",
  "surname": "Doe",
  "roleNames": ["ROLE_USER", "ROLE_ADMIN"]
}

### Create a new user
POST {{host}}/api/users
Content-Type: application/json

{
  "email": "asd@asd",
  "password": "12345678",
  "roleNames": []
}


### Update an existing user
PUT {{host}}/api/users/4
Content-Type: application/json

{
  "email": "new-email@example.com",
  "password": "new-password123",
  "roleNames": ["ROLE_USER"],
  "name": "New Name",
  "surname": "New Surname"
}


### Delete an existing user
DELETE {{host}}/api/users/1