### POST login
POST {{host}}/api/users/login
Content-Type: application/json

{
  "email": "funcad@mail5.com",
  "password": "12345678"
}

### POST logout
POST {{host}}/api/users/logout

### POST register
POST {{host}}/api/users/register
Content-Type: application/json

{
  "name": "Frank",
  "surname": "Cadillac",
  "email": "funcad@mail6.com",
  "password": "12345678",
  "roleNames": ["ROLE_USER", "ROLE_ADMIN"]
}

### Get all users
GET {{host}}/api/users


### Get a user by a specific ID
GET {{host}}/api/users/1


### Create a new user
POST {{host}}/api/users
Content-Type: application/json

{
  "email": "new@example.com",
  "password": "password123",
  "name": "John",
  "surname": "Doe",
  "roleNames": ["ROLE_USER", "ROLE_ADMIN"]
}

### Create a new user
POST {{host}}/api/users
Content-Type: application/json

{
  "email": "asd@asd",
  "password": "12345678",
  "roleNames": []
}


### Update an existing user
PUT {{host}}/api/users/4
Content-Type: application/json

{
  "email": "new-email@example.com",
  "password": "new-password123",
  "roleNames": ["ROLE_USER"],
  "name": "New Name",
  "surname": "New Surname"
}


### Delete an existing user
DELETE {{host}}/api/users/1